name: Main
on:
    pull_request:
jobs:
    size:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1
            - name: Size limit
              uses: andresz1/size-limit-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
    test:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Install pnpm
              run: npm i pnpm@latest -g
            - name: Install
              run: pnpm it
            - name: Test
              run: pnpm run test:ci
            - name: Test Report
              uses: dorny/test-reporter@v1
              with:
                  name: Jest Tests
                  path: reports/jest-*.xml
                  reporter: jest-junit
